  await page1.getByRole('menuitem', { name: 'General' }).click();
  await expect(page1.locator('#renderList')).toContainText('General');
  await page1.getByText('Enabled Signature Types').click();
  await expect(page1.locator('#renderList')).toContainText('Enabled Signature Types');
  await expect(page1.locator('#renderList')).toContainText('draw');
  await page1.getByText('typed').click();
  await expect(page1.locator('#renderList')).toContainText('typed');
  await expect(page1.locator('#renderList')).toContainText('upload');
  await expect(page1.locator('#renderList')).toContainText('default');
  await page1.getByRole('checkbox').nth(1).uncheck();
  await page1.getByRole('button', { name: 'Save' }).click();
  await expect(page1.locator('#renderList')).toContainText('Allow indexing of public profile by search engines');
  await expect(page1.getByLabel('', { exact: true })).toBeVisible();
  await page1.getByLabel('', { exact: true }).uncheck();
  await page1.getByLabel('', { exact: true }).check();
  await page.getByRole('menuitem', { name: 'Contactbook' }).click();
  await page.getByRole('button', { name: ' Settings' }).click();
  await page.getByRole('menuitem', { name: 'Preferences' }).click();
  await expect(page.locator('#panel-general')).toContainText('drawuploaddefault');